### ISSUE TITLE
Change in eslint-plugin-react no-did-mount-set-state enum makes react rules invalid

### ISSUE THREAD

**Issue by neilbenn** [nrkno/eslint-config-nrk#30]
nrk/rules/react:
	Configuration for rule "react/no-did-mount-set-state" is invalid:
	Value "allow-in-func" must be an enum value.

the non-default setting for <mode> is now disallow-in-function.

**Comment by janerikbr** [comment]
You're absolutely right, seems that the `allow-in-func` mode hasn't been available since `eslint-plugin-react` version [5.22](https://github.com/yannickcr/eslint-plugin-react/blob/v5.2.2/docs/rules/no-did-mount-set-state.md). I'll update our `eslint-config-nrk` repo in accordance to the latest version as soon as possible. Thanks!

**Comment by janerikbr** [comment]
This issue has been fixed and will be a part of our upcoming release of `eslint-plugin-nrk`.
